version: "3.8"
services:

  database:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/postgres/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    logging: 
      driver: none

  # database_administrator:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "bastian.p@outlook.com"
  #     PGADMIN_DEFAULT_PASSWORD: "12345"
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - "database"
  #   volumes:
  #     - ./pgadmin4/servers.json:/pgadmin4/servers.json
  #   logging: 
  #     driver: none

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ba_tester_image_dev
    depends_on:
      - "database"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}"
      WATCHPACK_POLLING: true
    volumes:
      - .:/app
