FROM node:24-alpine AS builder
WORKDIR /app/frontend
COPY ./frontend/package*.json ./
RUN npm ci --silent

FROM node:24-alpine AS dev
WORKDIR /app/frontend
COPY --from=builder /app/frontend/node_modules ./node_modules
COPY ./frontend ./frontend
COPY ./domain ./domain

EXPOSE 3000
CMD ["npm", "run", "dev"]
