export const env = {
  NEXT_PUBLIC_BACKEND_URL_FROM_CLIENT_SIDE: process.env.NEXT_PUBLIC_BACKEND_URL_FROM_CLIENT_SIDE,
  NEXT_PUBLIC_BACKEND_URL_FROM_SERVER_SIDE: process.env.NEXT_PUBLIC_BACKEND_URL_FROM_SERVER_SIDE,
};
