FROM node:24-alpine AS builder
WORKDIR /app/backend
COPY ./backend/package*.json ./
RUN npm ci --silent

FROM node:24-alpine AS dev
WORKDIR /app/backend
COPY --from=builder /app/backend/node_modules ./node_modules
COPY ./backend ./backend
COPY ./domain ./domain

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
