services:
  db-postgres:
    tty: true
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./src/repositories/postgres/migrations:/docker-entrypoint-initdb.d

  db-redis:
    tty: true
    image: redis
    env_file:
      - .env
    ports:
      - "6379:6379"

  ab-tester-svc:
    build:
      dockerfile: Dockerfile.dev
    image: ba-tester/service
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DOMAIN: ${DOMAIN}
      DATABASE_URL_POSTGRES: ${DATABASE_URL_POSTGRES}
      DATABASE_URL_REDIS: ${DATABASE_URL_REDIS}
      SALT_ROUNDS: ${SALT_ROUNDS}
      SUPER_ADMIN_EMAIL: ${SUPER_ADMIN_EMAIL}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}
    ports:
      - "4000:4000"
    depends_on:
      - db-postgres
      - db-redis
    volumes:
      - /app/node_modules
      - .:/app

  ab-tester-ui:
    tty: true
    command: npm run dev
    build:
      context: ../ab-tester-ui
      dockerfile: Dockerfile.dev
    image: ba-tester/ui
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_BACKEND_URL_SERVER_SIDE: ${NEXT_PUBLIC_BACKEND_URL_SERVER_SIDE}
      NEXT_PUBLIC_BACKEND_URL_CLIENT_SIDE: ${NEXT_PUBLIC_BACKEND_URL_CLIENT_SIDE}
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ../ab-tester-ui:/app