FROM node:24-alpine AS builder
WORKDIR /app/ab-tester-svc
COPY ./ab-tester-svc/package*.json ./
RUN npm ci --silent

FROM node:24-alpine AS dev
WORKDIR /app/ab-tester-svc
COPY --from=builder /app/ab-tester-svc/node_modules ./node_modules
COPY ./ab-tester-svc ./ab-tester-svc
COPY ./ab-tester-types ./ab-tester-types

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
